#!/bin/sh

pwd
ls
# echo 12345
# /root/benchmark/stream
# ifconfig -a
# /root/redis/redis-serve
# free -mh
# ls /dev

insmod /root/penglai/penglai.ko 
cat /proc/misc
lsmod
# major: 10 - misc dev; minor: 63 - specify the penglai dev
mknod /dev/penglai_enclave_dev c 10 63 
ls /dev
ls /root
echo Penglai Enclave Start
echo -------------------------------------------------------
/root/host_malware /root/fdi_attack_origin
# /root/host_malware /root/fdi_attack_defend
# /root/host /root/count