APP = rijndael
APP_C_SRCS = aes.c aesxam.c
EXTRA_CLEAN = $(APP).dump
include $(PENGLAI_SDK)/app.mk

# rijndael: aes.c aes.h aestab.h aesxam.c Makefile
# 	gcc -static -O3 -o rijndael aes.c aesxam.c

# clean:
# 	rm -rf rijndael output*
